### ISSUE TITLE
How are you converting error from pixel to meter

### ISSUE THREAD

**Issue by avijit9** [vvanirudh/social-lstm-pytorch#1]
In your paper, you have reported errors in terms of meter. In your code where are you doing this conversion?

**Comment by vvanirudh** [comment]
I did it using a different script but its basically the homography transformation. Refer to the issue in the tensor flow social lstm repo

**Comment by erichhhhho** [comment]
Could you pls explain the normalization details of this data? It is definitely not normalized by width and height.

**Comment by avijit9** [comment]
This is the formula he has used after interpolation. `(2*x/height - 1, 2*y/width - 1)`

**Comment by erichhhhho** [comment]
Not exactly, this is for the pixel coordinate, it should've normalized by the max and min. @avijit9

**Comment by avijit9** [comment]
@erichhhhho  You can refer this issue: https://github.com/vvanirudh/social-lstm-tf/issues/12

**Comment by erichhhhho** [comment]
Yes. I read it before. but that's the case for pixel. Did you directly normalize the meter data with width and height? However, I got different data after processing/
