### ISSUE TITLE
bugs in function 'get_mean_error' in helper.py

### ISSUE THREAD

**Issue by piaozhx** [vvanirudh/social-lstm-pytorch#5]
Thanks for the great implement of social-LSTM. However, I found a bugs when I use the function 'get_mean_error' in [here](https://github.com/vvanirudh/social-lstm-pytorch/blob/master/social_lstm/helper.py#L191), I think counter should be assigned zero where next tstep comes.

**Comment by vvanirudh** [comment]
Updated

**Comment by ZongweiZhou1** [comment]
@piaozhx 
Hey, when i run the sample.py, I find the average displacement error and the Final displacement error are the same order of magnitude. But in the paper, average displacement error is much smaller than final displacement error.
Could you give me some advices, pls?
